version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
    environment:
      - NODE_ENV=production
    command: ["vite", "--host", "0.0.0.0", "--port", "3000"]

networks:
  default:
    driver: bridge
