version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
    environment:
      - NODE_ENV=production
    command: ["serve", "-s", "build", "-l", "0.0.0.0:3000"]

networks:
  default:
    driver: bridge
