name: Deploy Frontend to VPS

on:
  push:
    branches: [production]

jobs:
  deploy-fe:
    runs-on: ubuntu-latest

    steps:
      - name: SSH Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            cd /root/services/frontend-web || git clone https://github.com/nguyenKhangvn/frontend-web.git /root/services/frontend-web && cd /root/services/frontend-web
            git fetch origin
            git checkout production
            git pull
            npm install
            npm run build
            docker compose down
            docker compose up -d --build
